---
title: "Data and models for Lai et al. (2021) *Ecol. Lett.*"
output: github_document
---

`r badger::badge_custom("zenodo", "10.5281/zenodo.5183031", "yellow", "https://doi.org/10.5281/zenodo.5183031")`
`r badger::badge_custom("article", "10.1111/ele.13784", "green", "https://doi.org/10.1111/ele.13784")`
`r badger::badge_license("MIT")`

# Preamble

Welcome! This is a repository for the data and models in our paper:

> Lai, H. R., Craven, D., Hall, J. S., Hui, F. K. C., & Breugel, M. (2021). Successional syndromes of saplings in tropical secondary forests emerge from environment‐dependent trait--demography relationships. *Ecology Letters*, 24(9), 1776--1787. DOI: 10.1111/ele.13784

# Usage 

You could either [clone](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) our GitHub repository or, if you're unfamiliar with GitHub, download the [released zip file](https://github.com/hrlai/Lai_et_al_2021_EcolLett_Trait_Age/releases).

The `R` script `R/reproducibility.R` is basically all you need to extract data or examine model outputs from the two models: the recruitment model `data/recruitment_model.rds` and the mortality model `data/mortality_model.rds`. Please see the script for instructions. The rest of the scripts in the `R` folder are axillary scripts to mainly to reproduce figures.

# Citation

Lai, H. R., Craven, D., Hall, J. S., Hui, F. K. C., & Breugel, M. (2021). Successional syndromes of saplings in tropical secondary forests emerge from environment‐dependent trait--demography relationships. *Ecology Letters*, 24(9), 1776--1787.

# Contact

Please feel free to post your issue in the [Issue page](https://github.com/hrlai/Lai_et_al_2021_EcolLett_Trait_Age/issues).